import { Project } from './index';

export const webProjects: Project[] = [
  {
    id: 'concordia-college',
    title: 'Concordia College Management System',
    description:
      'A full-stack, role-based college management system — a Next.js web app paired with a Flutter mobile app — that manages the complete student lifecycle from admission and fees to academics, teaching, and result generation across 7 distinct roles.',
    longDescription:
      'The Concordia College Admin Management System is a comprehensive, role-based platform that manages the entire student lifecycle — from admission through fee collection, academic administration, teaching, and result generation. Delivered as a full-stack solution with a Next.js web application and a Flutter mobile application, it enforces strict, non-overlapping permissions so sensitive actions (like finalizing a fee) can only be performed once, by the correct role, and cannot be altered downstream.\n\nThe system defines seven roles: Admin (top-level oversight), Admission Office (enrolls students and finalizes a permanently locked base fee), Accountant (confirms payments, auto-generates student logins, issues challans, splits fees into installments, and adds miscellaneous charges), Academic Office (manages teachers, timetables, date sheets, announcements, and result-card generation), Teacher (attendance, marks entry, and feedback for allocated classes only), and view-only Student and Parent portals mirrored to the linked student\'s data.\n\nA standout workflow is the monthly test and result pipeline: Academic publishes the date sheet, teachers enter subject-wise marks, Academic reviews all submitted subjects, and the system auto-calculates totals and generates a publishable result card visible to every student. The result is a secure, auditable administration platform with clean separation of duties across web and mobile.',
    role: 'Full Stack Developer (Next.js Web & Flutter Mobile)',
    technologies: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Flutter',
      'Dart',
      'REST APIs',
      'PostgreSQL',
    ],
    features: [
      'Role-Based Access for 7 User Types (Admin, Admission, Accountant, Academic, Teacher, Student, Parent)',
      'Student Admission with Locked, One-time Base-Fee Finalization',
      'Fee Challans, 3–4 Installment Splits & Miscellaneous Charges',
      'Auto-generated Student Logins (Roll No + default password)',
      'Timetables, Date Sheets & Role-wide Announcements',
      'Monthly Tests → Teacher Marks Entry → Auto Result-Card Generation',
      'Attendance, Results & Feedback for Allocated Classes',
      'View-only Student & Parent Portals',
      'Cross-platform: Next.js Web App + Flutter Mobile App',
    ],
    video: '/projects/Concordia College Management System.mp4',
    liveUrl: 'https://www.concordiacollegecanalcampus.com/',
    status: 'completed',
    category: 'web-app',
  },
  {
    id: 'energybits',
    title: 'ENERGYbits',
    description:
      'A Shopify store for the world\'s #1 algae tablet brand, where I automated SEO, AEO, and GEO optimization, AI video generation, and blog content publishing.',
    longDescription:
      'ENERGYbits® is the world\'s #1 algae tablet brand, offering 100% pure spirulina and chlorella tablets across product lines like ENERGYbits (energy & protein), RECOVERYbits (detox & immune support), BEAUTYbits (skin, hair & nails), and VITALITYbits (balanced wellness). The brand emphasizes single-ingredient purity — "Fuel Your Body at the Cellular Level" — with organic, third-party-tested, doctor-endorsed nutrition.\n\nFor their Shopify store, I automated the content and growth pipeline end to end — SEO, AEO (answer-engine optimization), and GEO (generative-engine optimization), AI-driven video generation, and automated blog content publishing. The workflows keep marketing content flowing consistently and optimize product and educational pages for both traditional search and AI-driven answer engines.\n\nThe outcome is a content-rich Shopify presence with automated video and blog production plus continuous SEO/AEO/GEO improvements that strengthen organic discoverability and brand visibility across modern search ecosystems.',
    role: 'Shopify SEO & Automation Specialist',
    technologies: ['Shopify', 'Automation', 'SEO', 'AEO', 'GEO', 'AI Video Generation', 'Blog Content', 'Google Analytics'],
    features: [
      'SEO, AEO & GEO Optimization',
      'AI-driven Video Generation',
      'Automated Blog Content Publishing',
      'Automated Content Pipeline',
      'Product & Educational Page Optimization',
      'Shopify Store Enhancements',
      'Organic Growth & Visibility Tracking',
    ],
    video: '/projects/Energybits.mp4',
    liveUrl: 'https://energybits.com/',
    status: 'completed',
    category: 'web-app',
  },
  {
    id: 'harmony-med-spa',
    title: 'Harmony Med Spa',
    description:
      'A Next.js website for a Sarasota med spa where I automated content uploading, blog publishing, and custom site improvements optimized for SEO, AEO, and GEO.',
    longDescription:
      'Harmony Med Spa is a full-service medical spa in Sarasota, Florida, led by a board-certified aesthetic nurse practitioner and known for a natural, holistic approach to beauty. Their services span lasers and lights, injectables, facials and peels, body treatments, wellness, and retail skincare, alongside online booking, a blog, memberships, and a patient center.\n\nBuilt on Next.js, the site\'s content and publishing pipeline was fully automated — automated content and page uploading, automated blog content publishing, and ongoing custom improvements to the site. The work was optimized for modern search visibility across SEO (traditional search), AEO (answer-engine optimization), and GEO (generative-engine optimization), so the med spa\'s services and content surface well in both classic search results and AI-driven answers.\n\nThe outcome is a fast, well-structured, content-rich Next.js website with automated publishing workflows that keep content up to date while continuously improving organic discoverability.',
    role: 'Full Stack Developer & SEO Automation Specialist',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Automation', 'SEO', 'AEO', 'GEO'],
    features: [
      'Automated Content & Page Uploading',
      'Automated Blog Content Publishing',
      'Custom Site Improvements',
      'SEO, AEO & GEO Optimization',
      'Online Booking Integration',
      'Membership & Patient Center',
      'Content Pipeline Automation',
    ],
    video: '/projects/Harmony Medspa.mp4',
    liveUrl: 'https://www.harmonymedspafl.com/',
    status: 'completed',
    category: 'web-app',
  },  {
    id: 'tristate-auto-crm',
    title: 'TriState Auto CRM',
    description:
      'A full-featured CRM for automotive dealerships that automates the entire customer journey — from vehicle financing applications and soft credit checks to meeting scheduling and automated email/SMS communications.',
    longDescription:
      'TriState Auto CRM is a comprehensive customer relationship management system built for automotive dealerships to manage the complete customer journey — from application submission through credit evaluation, meeting scheduling, and follow-up communications.\n\nCustomers submit a multi-step vehicle financing application with real-time validation (SSN, email, phone) and SMS opt-in, which automatically triggers a soft credit pull via the 700Credit API, runs automated tier grading based on credit score, financials, and employment status, and sends a welcome email/SMS with a self-service booking link. A powerful admin dashboard gives dealership staff role-based control (Manager, Admin, Staff) over applications, applicants, meetings, physical-visit tracking, two-way SMS chat, and a scheduling engine with templates, rules, and a drag-and-drop notification calendar.\n\nAutomated communications run through SendGrid (email) and Twilio (SMS), while an analytics dashboard surfaces total applications, tier distribution, and scheduled meetings. Security is built in throughout — encrypted SSNs and sensitive data, session-based authentication with CSRF protection, and HTTPS across all communication.',
    role: 'Full Stack Developer',
    technologies: [
      'React',
      'TypeScript',
      'Vite',
      'Django',
      'Django REST Framework',
      'PostgreSQL',
      'SendGrid',
      'Twilio',
      '700Credit API',
    ],
    features: [
      'Multi-step Financing Application with Real-time Validation',
      'Automated Tier Grading & 700Credit Soft Credit Pulls',
      'Self-service Meeting Scheduler with Double-booking Prevention',
      'Automated Email (SendGrid) & SMS (Twilio) Notifications',
      'Two-way SMS Chat with Customers',
      'Role-based Admin Dashboard (Manager / Admin / Staff)',
      'Scheduling Engine with Templates, Rules & Drag-and-drop Calendar',
      'Physical Visit Tracking & Check-ins',
      'AI Chatbot on Public Pages',
      'Analytics & Reporting Dashboard',
    ],
    video: '/projects/Tristate Project.mp4',
    liveUrl: 'https://www.tristateautosales.com/',
    status: 'completed',
    category: 'web-app',
  },
  {
    id: 'modern-law',
    title: 'Modern Law',
    description:
      'A modern, automation-built WordPress website for an Arizona family law firm — showcasing practice areas, attorney profiles, online consultation booking, and free client tools.',
    longDescription:
      'Modern Law is a full-service family law firm based in Arizona ("Not Your Ex\'s Law Firm — Compassion First, Innovation Always") with 20+ attorneys across Phoenix, Scottsdale, Mesa, Gilbert, Peoria, Tucson, and Yuma. The website was built on WordPress and streamlined with automation to present the firm\'s services and convert visitors into consultations.\n\nThe site covers the firm\'s full range of practice areas — divorce and separation, child custody and support, spousal maintenance, estate planning, domestic violence and protective orders, division of assets, prenuptial/postnuptial agreements, guardianship, adoption, appeals, and mediation. It features online appointment scheduling, a detailed attorney and staff directory, client testimonials, and a suite of free interactive tools including a child-support calculator, spousal-maintenance estimator, and co-mingled property calculator, plus e-books, a podcast, and DIY divorce resources.\n\nDelivered as a responsive, content-rich marketing site with automated workflows for scheduling and client intake, it emphasizes flexible service models, holistic client wellness, and 24/7 family-law support.',
    role: 'Web Developer (WordPress & Automation)',
    technologies: ['WordPress', 'Elementor', 'Automation', 'SEO', 'Responsive Design'],
    features: [
      'Automation-built WordPress Website',
      'Practice Areas & Legal Services Pages',
      'Attorney & Staff Directory (20+ attorneys)',
      'Online Consultation Booking',
      'Free Client Tools (Support & Property Calculators)',
      'Client Testimonials & Resources',
      'Podcast, E-books & DIY Divorce Navigator',
      'Multi-location, Responsive Design',
    ],
    video: '/projects/Modern Law Website.mp4',
    videoPlaybackRate: 1.5,
    liveUrl: 'https://mymodernlaw.com/',
    status: 'completed',
    category: 'web-app',
  },
  {
    id: 'signal-law',
    title: 'Signal Law',
    description:
      'An automation-built WordPress website for an independent corporate intelligence and investigations firm, presenting proxy research, governance investigations, and company intelligence.',
    longDescription:
      'Signal (Signal Independent Corporate Intelligence) is an independent corporate intelligence and investigations firm focused on public-company governance, proxy analysis, and securities-disclosure risk research — "The public record shows the facts. Signal finds the pattern." The website was built on WordPress and streamlined with automation to publish and organize the firm\'s investigations and research.\n\nThe site presents the firm\'s core offerings: proxy intelligence with ballot-level FOR/AGAINST/WITHHOLD recommendations delivered within 48 hours, real-time company intelligence dashboards and monitoring, and deep-dive investigations into disclosure, governance, and control failures. Content is organized into Platform, Proxy Intelligence, Research, Investigations, and individual Company profiles and timelines, with email subscriptions for proxy recommendations and research updates.\n\nDelivered as a responsive, research-driven site, it emphasizes structural independence (no issuer revenue), named analysis with visible methodology and source documentation, and permanent, tamper-evident records published before each vote.',
    role: 'Web Developer (WordPress & Automation)',
    technologies: ['WordPress', 'Elementor', 'Automation', 'SEO', 'Responsive Design'],
    features: [
      'Automation-built WordPress Website',
      'Investigations & Research Publishing',
      'Proxy Intelligence with Ballot Recommendations',
      'Real-time Company Intelligence Dashboards',
      'Company Profiles & Timelines',
      'Email Subscription for Research Updates',
      'Named Analysis with Source Documentation',
      'Responsive, Research-driven Design',
    ],
    video: '/projects/sIGNAL lAW.mp4',
    liveUrl: 'https://www.signallawgroup.com/',
    status: 'completed',
    category: 'web-app',
  },
  {
    id: 'kenetics',
    title: 'Kenetics',
    description: 'A web-based remote therapeutic monitoring (RTM) platform for patients and therapists.',
    longDescription:
      'Kenetics is a web-based remote therapeutic monitoring (RTM) platform designed to streamline communication and care between patients and therapists. It allows patients to follow therapist-assigned exercises, track their progress, and communicate directly with healthcare providers, while therapists can monitor activity, assign programs, review reports, and manage billing and scheduling—all within one unified system.\n\nThe outcome of Kenetics is an efficient, user-friendly portal where patients experience improved accountability and motivation in their recovery journey, and therapists gain a comprehensive dashboard to oversee patient progress, optimize care plans, and simplify administrative workflows, ultimately improving healthcare delivery and patient outcomes.',
    role: 'Junior Full Stack Developer',
    technologies: ['React', 'Vite', 'Tailwind CSS', 'Node.js', 'TypeScript'],
    features: [
      'Patient Portal with Exercise Tracking',
      'Therapist Dashboard for Monitoring',
      'Direct Communication Tools',
      'Billing & Scheduling Management',
      'Progress Reports & Analytics',
    ],
    image: '/projects/kenetics.PNG',
    liveUrl: 'http://d26f1dm6kt7m07.cloudfront.net/',
    githubUrl: 'https://github.com/qayyums3116/',
    status: 'completed',
    category: 'web-app',
  },
  {
    id: 'gaeilgeoir-ai',
    title: 'Gaeilgeoir.AI',
    description:
      'A digital language-learning platform focused on teaching Irish (Gaeilge) with gamified, AI-powered lessons.',
    longDescription:
      'Gaeilgeoir.AI is a digital language-learning platform focused on teaching Irish (Gaeilge). It offers personalized, gamified lessons based on everyday scenarios, real-life conversations, and pronunciation practice. Learners benefit from interactive quizzes, video lessons, and progress tracking designed for all levels. The platform also includes a three-day free trial, subscription model (~€9.99/month), and targeted resources for the Irish Leaving Cert oral exam.\n\nThe outcome is an engaging, AI-driven solution for both beginners and advanced learners to master Irish with real-world practice and measurable progress.',
    role: 'Junior Full Stack Developer',
    technologies: ['React', 'Vite', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Express', 'MongoDB'],
    features: [
      'Gamified Language Lessons',
      'Real-life Conversation Practice',
      'Interactive Quizzes & Video Lessons',
      'Progress Tracking Dashboard',
      'Subscription & Free Trial System',
      'Leaving Cert Oral Exam Resources',
    ],
    image: '/projects/gaeilgeoir.PNG',
    liveUrl: 'https://learn.gaeilgeoir.ai/',
    githubUrl: 'https://github.com/qayyums3116/',
    status: 'completed',
    category: 'web-app',
  },
    {
    id: 'psiadirondack',
    title: 'PsiAdirondack Intelligence',
    description:
      'A next-gen platform for Generative Engine Optimization (GEO), automating content publishing and SEO across platforms.',
    longDescription:
      'PsiAdirondack Intelligence is a next-generation platform designed to help businesses dominate the AI-driven search era through Generative Engine Optimization (GEO). It automates publishing customer content across platforms like Wikipedia, Quora, Reddit, and Stack Overflow while optimizing it for SEO and GEO to ensure top visibility in generative AI searches (e.g., ChatGPT, Google SGE, Perplexity). With built-in generative AI for content creation, predictive modeling for performance forecasting, a CRM for managing uploads, and real-time analytics for monitoring visibility, citations, and engagement, the platform empowers businesses to enhance brand presence, track results, and continuously adapt for maximum impact in AI-powered search ecosystems.',
    role: 'Junior Full Stack Developer',
    technologies: ['React', 'Vite', 'TypeScript', 'Tailwind CSS'],
    features: [
      'Generative Engine Optimization (GEO)',
      'Multi-platform Publishing',
      'Built-in Generative AI',
      'CRM for Content Management',
      'Real-time Analytics & Forecasting',
    ],
    image: '/projects/PSI.PNG',
    liveUrl: 'https://psiadirondack.netlify.app/',
    githubUrl: 'https://github.com/qayyums3116/',
    status: 'completed',
    category: 'web-app',
  },
  {
  id: 'kenetics-landing',
  title: 'Kenetics (Landing Page)',
  description: 'A modern landing page for Kenetics RTM platform, highlighting features for patients and therapists.',
  longDescription:
    'The Kenetics Landing Page was designed to showcase the Remote Therapeutic Monitoring (RTM) platform with a clean, modern interface. It emphasizes the value proposition for patients and therapists, highlighting exercise tracking, therapist dashboards, communication tools, and administrative workflows. Unlike the full web app, this project focuses on presenting the product vision, features, and benefits in a visually engaging and responsive manner to drive user engagement and conversions.',
  role: 'Junior Full Stack Developer',
  technologies: ['React', 'Vite', 'TypeScript', 'Tailwind CSS'],
  features: [
    'Responsive Landing Page Design',
    'Highlight of RTM Features',
    'Modern UI with Tailwind CSS',
    'Optimized for Conversions',
  ],
  image: '/projects/RTM.PNG',
  liveUrl: 'https://kenetics.netlify.app/',
  githubUrl: 'https://github.com/qayyums3116/',
  status: 'completed',
  category: 'web-app',
},

  {
    id: 'meade-rewards',
    title: 'Meade Rewards (Landing Page)',
    description:
      'A modern fintech landing page showcasing AI-driven financial management and business growth tools.',
    longDescription:
      'Meade Rewards is an all-in-one fintech platform designed to empower individuals and businesses to achieve financial freedom with ease. The landing page highlights powerful features such as AI-driven financial management, credit score insights, investment planning, funding opportunities, and exclusive membership benefits. Users can connect with financial mentors, leverage an AI-powered chatbot for 24/7 support, and even hire top professionals to scale their business. With a modern design, intuitive navigation, testimonials from real clients, and seamless app download links, the Meade Rewards landing page showcases a trusted solution for simplifying finances, building connections, and unlocking long-term growth.',
    role: 'Junior Full Stack Developer',
    technologies: ['HTML5', 'CSS3', 'Bootstrap'],
    features: [
      'AI-Driven Financial Management',
      'Credit Score Insights',
      'Investment Planning',
      'Exclusive Membership Benefits',
      'AI Chatbot & Mentor Access',
    ],
    image: '/projects/MR.PNG',
    liveUrl: 'https://codesquad-ai.github.io/MEADE-REWARDS/',
    githubUrl: 'https://github.com/codesquad-ai/MEADE-REWARDS',
    status: 'completed',
    category: 'web-app',
  },

  {
    id: 'frontline-dental',
    title: 'Frontline Dental (Landing Page)',
    description: 'An AI-powered dental care landing page focusing on precision, personalization, and efficiency.',
    longDescription:
      'Frontline Dental is an AI-powered dental care platform aiming to redefine oral health delivery through precision, personalization, and operational efficiency. It combines high-resolution imaging, diagnostics, and treatment planning driven by continuously learning AI models with human oversight. Patients follow tailored care pathways—preventive to advanced—to receive coordinated treatment, supported by features like virtual consults, risk stratification, real-time imaging analytics, inventory and insurance automation, and strong data security.\n\nThe goal: better patient outcomes, more engaged patients, lower clinic overhead, and scalable, sustainable dental operations.',
    role: 'Junior Full Stack Developer',
    technologies: ['HTML5', 'CSS3', 'Bootstrap'],
    features: [
      'AI-Powered Diagnostics & Imaging',
      'Virtual Consultations',
      'Personalized Care Pathways',
      'Insurance & Inventory Automation',
      'Data Security & Risk Stratification',
    ],
    image: '/projects/f-d.PNG',
    liveUrl: 'https://codesquad-ai.github.io/Frontline-Dental/',
    githubUrl: 'https://github.com/codesquad-ai/Frontline-Dental',
    status: 'completed',
    category: 'web-app',
  },
];
